import { Inter } from "next/font/google";

import "./globals.css";

import { SidebarProvider } from '@/context/SidebarContext';
import ClientLayout from '@/components/ClientLayout';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            
            <body>
                <SidebarProvider>
                    <ClientLayout>
                        {children}
                    </ClientLayout>
                </SidebarProvider>
            </body>
            
        </html>
    );
}
